import { APIMetadataEntry } from '../types/api/api';
import { KulCardEventPayload } from '../types/ketchup-lite/components';
import { Card } from '../types/widgets/card';
import { CardsWithChip } from '../types/widgets/cardsWithChip';
export declare const CARD_PROPS_TO_SERIALIZE: string[];
export declare const cardPlaceholders: (widget: Card | CardsWithChip, count: number) => void;
export declare const fetchModelMetadata: (models: APIMetadataEntry[], forcedSave?: boolean) => Promise<Partial<HTMLKulCardElement>[]>;
export declare const cardHandler: (container: HTMLDivElement, propsArray: Partial<HTMLKulCardElement>[]) => number;
export declare const getCardProps: (container: HTMLDivElement) => Partial<HTMLKulCardElement>[];
export declare const createCard: () => HTMLKulCardElement;
export declare const cardEventHandler: (e: CustomEvent<KulCardEventPayload>) => void;
export declare const contextMenuHandler: (card: HTMLKulCardElement, e: MouseEvent) => void;
