import { KulButtonEventPayload, KulImageviewerEventPayload, KulSliderEventPayload, KulSwitchEventPayload } from '../types/ketchup-lite/components';
import { KulDataColumn, KulDataDataset, KulDataNode } from '../types/ketchup-lite/managers/kul-data/kul-data-declarations';
import { ImageEditorWidgetActionButtons, ImageEditorWidgetSliderConfig, ImageEditorWidgetStatus, ImageEditorWidgetToggleConfig, ImageEditorWidgetUpdateCallback } from '../types/widgets';
export declare const buttonEventHandler: (imageviewer: HTMLKulImageviewerElement, actionButtons: ImageEditorWidgetActionButtons, grid: HTMLDivElement, e: CustomEvent<KulButtonEventPayload>) => Promise<void>;
export declare const imageviewerEventHandler: (settings: HTMLDivElement, node: NodeType, e: CustomEvent<KulImageviewerEventPayload>) => Promise<void>;
export declare const sliderEventHandler: (updateCb: ImageEditorWidgetUpdateCallback, e: CustomEvent<KulSliderEventPayload>) => Promise<void>;
export declare const switchEventHandler: (updateCb: ImageEditorWidgetUpdateCallback, e: CustomEvent<KulSwitchEventPayload>) => Promise<void>;
export declare const prepSettings: (settings: HTMLDivElement, node: KulDataNode, imageviewer: HTMLKulImageviewerElement) => void;
export declare const createSlider: <ID extends string>(data: ImageEditorWidgetSliderConfig<ID>, updateCb: ImageEditorWidgetUpdateCallback) => HTMLKulSliderElement;
export declare const createToggle: <ID extends string>(data: ImageEditorWidgetToggleConfig<ID>, updateCb: ImageEditorWidgetUpdateCallback) => HTMLKulSwitchElement;
export declare const getPathColumn: (dataset: KulDataDataset) => KulDataColumn | null;
export declare const getStatusColumn: (dataset: KulDataDataset) => KulDataColumn | null;
export declare const resetSettings: (settings: HTMLElement) => Promise<void>;
export declare const setGridStatus: (status: ImageEditorWidgetStatus, grid: HTMLDivElement, actionButtons: ImageEditorWidgetActionButtons) => void;
